enum OutputStrings
{
	GAME_NEW_OR_LOAD,
	OPTION_NOT_FOUND,
	PICK_VALID_OPTION,
	ENTER_MAIN_CHARACTER_NAME,
	ENTER_SECOND_CHARACTER_NAME,
	WELL,
	KICKASS,
	READY_OPTIONS,
	COUNTER_ATTACK_DAMAGE,
	ATTACK_DAMAGE,
	STAT_CHANGE
};